import Image from "next/image";
import PageHero from "@/app/components/PageHero";
import SectionTitle from "@/app/components/SectionTitle";

export const metadata={title:"Admissions",description:"EYEG admissions requirements, forms, age groups and timings."};
const childDocs=["Passport copy with valid visa page (2)","Emirates ID copy (2)","Birth Certificate copy (2)","Recent passport-size photos (8)","Immunisation Record copy (2)","Infant photo (1)","Recent stamp-size photos (2)"];
const parentDocs=["Passport copy with visa page (1 each)","Emirates ID copy (1 each)","Recent passport-size photos (1 each)","Emirates ID of authorised pick-up person","Passport photo of authorised pick-up person"];
const forms=[["NDNELC Admission Form","NDNELC-Admission-Form.pdf"],["Health Declaration Form","HEALTH-DECLARATION-FORM.pdf"],["Transport Form","TRANSPORT-FORM.pdf"],["Authorised Pick Up Form","AUTHORISED-PICK-UP-FORM.pdf"]];
export default function AdmissionsPage(){return <main><PageHero title="Admissions" image="/assets/Admissions11.jpg" imageAlt="EYEG admissions" titleClass="text-[#ffae01] drop-shadow"/><section id="page-content" className="bg-[#f2f0b8] px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-6xl"><SectionTitle>Our Early Learning Centre enrolls students all through the year</SectionTitle><h3 className="heading mt-7 text-2xl">Required Documents for the Admission Process</h3><div className="mt-10 grid gap-12 md:grid-cols-2"><DocumentList title="The Child’s" items={childDocs}/><DocumentList title="The Parent’s" items={parentDocs}/></div></div></section><section className="px-5 py-20 text-center sm:px-8 lg:px-14"><div className="mx-auto max-w-3xl"><Image src="/assets/NDN2-1.png" alt="New Dubai Nursery" width={500} height={220} className="mx-auto h-auto w-80"/><h2 className="heading mt-8 text-3xl">NDNELC Forms</h2><div className="mt-6 divide-y divide-slate-200 text-left">{forms.map(([name,file])=><a key={file} className="flex items-center justify-between px-4 py-4 font-bold text-slate-600 hover:bg-slate-50 hover:text-[#168ac2]" href={`/forms/${file}`} target="_blank">{name}<span className="text-xs text-[#168ac2]">PDF ↗</span></a>)}</div></div></section><section className="bg-slate-50 px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-4xl"><SectionTitle>Timings and Age Group</SectionTitle><div className="mt-8 space-y-4 leading-7 text-slate-600"><p><b>Age Group:</b> 2 to 6 years</p><p><b>Timings:</b> 8:00 a.m. to 12:00 p.m. Monday–Thursday; 8:00 a.m. to 10:30 a.m. Friday</p><p><b>Extended Care:</b> available until 6:00 p.m. without transport</p><p>Updated documents must be submitted promptly by email for Ministry records.</p></div></div></section></main>}
function DocumentList({title,items}){return <div><h2 className="heading text-3xl">{title}</h2><ol className="mt-6 list-decimal space-y-3 pl-6 text-slate-700">{items.map(x=><li key={x}>{x}</li>)}</ol></div>}
