import Image from "next/image";
import Link from "next/link";
import Gallery from "./components/Gallery";
import HomeHero from "./components/HomeHero";
import SectionTitle from "./components/SectionTitle";
import TestimonialSlider from "./components/TestimonialSlider";

const aspects=[
  ["1.Approved.png","Licensed, registered and approved by the concerned local governing bodies."],["2.-Transport.png","RTA-compliant transport with female supervision."],["3.Sports-Fitness.png","Early Years Fitness Programme guided by professional coaches."],["4.Computer.png","Computer Fun to keep pace with modern technology."],["5.Play-Area.png","Interactive indoor and outdoor play areas."],["6.Soft-Play-Area.png","Safe and secure soft play area."],["7.-Music.png","Aerobics and music times."],["8.Gym_.png","Junior Gym Facility."],["9.Graduation-Day.png","Graduation day showcases children’s talent."],["10.Fitness.png","Sporting events nurture fitness from an early age."],["11.Parent-Teacher.png","Regular Parent Teacher Meetings."],["12.Party_.png","Periodical party fun times."],["13.School-Trip.png","Monthly outdoor learning trips."],["14.Summer.png","Special summer activities."],["15.Reading.png","Reading areas that build a love for books."]
];
const galleries=["/api/media/assets/2I6A9821-768x512.jpg","/api/media/assets/WhatsApp-Image-2024-06-11-at-11.40.46-300x225.jpeg","/api/media/assets/20240621_100917-300x225.jpg","/api/media/assets/HAN03166-1-300x200.jpg","/api/media/assets/WhatsApp-Image-2025-06-17-at-4.26.10-PM-300x200.jpeg"];

export default function Home(){return <main><HomeHero/><section className="px-5 py-20 sm:px-8 lg:px-14"><p className="text-center text-xs font-black uppercase tracking-[.25em] text-[#168ac2]">EYEG — Early Years Education Group</p><div className="mx-auto mt-10 grid max-w-6xl items-center gap-10 md:grid-cols-2"><Image src="/api/media/assets/LearnMore_homeiiii.png" alt="Children learning and playing" width={595} height={613} className="h-auto w-full"/><div className="text-center"><SectionTitle center>About EYEG</SectionTitle><p className="mx-auto mt-7 max-w-xl text-lg font-light leading-8 text-slate-600">Welcome to EYEG, a colourful enchanting world for children aged 2 to 6 years. We provide quality early childhood education along with fun and play.</p><Link href="/about-us" className="mt-8 inline-flex rounded-lg bg-[#168ac2] px-6 py-3 text-xs font-black uppercase tracking-wider text-white hover:bg-[#1076a6]">Learn More</Link></div></div></section><div className="h-32 bg-[#43cec9] bg-[url('/api/media/assets/Home_Sketch1.png')] bg-cover bg-center sm:h-48"/>
<section className="px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-6xl"><SectionTitle center>Key Aspects</SectionTitle><p className="mx-auto mt-7 max-w-4xl text-center text-lg font-light leading-8 text-slate-600">EYEG transforms children’s magic years into fun-filled activities that build confidence, self-esteem and a lifelong excitement for learning.</p><div className="mt-14 grid gap-x-10 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{aspects.map(([icon,text])=><article key={icon} className="text-center"><Image src={`/api/media/assets/${icon}`} alt="" width={71} height={71} className="mx-auto h-[71px] w-[71px] object-contain"/><p className="mx-auto mt-4 max-w-sm text-sm leading-6 text-slate-700">{text}</p></article>)}</div></div></section>
<section className="bg-slate-100 bg-[url('/api/media/assets/background-12.png')] bg-cover bg-center px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-6xl rounded-3xl bg-white/90 px-6 py-12 backdrop-blur-sm sm:px-12"><SectionTitle center>Parents as Partners</SectionTitle><TestimonialSlider/></div></section>
<section className="px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-6xl"><SectionTitle center>Newsletters</SectionTitle><div className="mt-12 grid gap-12 sm:grid-cols-3">{[["2–3 Years","Screenshot-2025-12-23-114921-212x300.png"],["3–4 Years","Screenshot-2025-12-23-115925-211x300.png"],["4–6 Years","Screenshot-2025-12-23-120349-213x300.png"]].map(([age,img])=><article className="text-center" key={age}><h3 className="heading text-2xl text-slate-700">{age}</h3><Image src={`/api/media/assets/${img}`} alt={`Newsletter for ages ${age}`} width={213} height={300} className="mx-auto mt-5 shadow-xl transition hover:-translate-y-1"/><Link href="/important-dates" className="mt-5 inline-block text-xs font-black uppercase text-[#168ac2]">View Updates</Link></article>)}</div></div></section>
<section className="bg-slate-50 px-5 py-20 sm:px-8 lg:px-14"><div className="mx-auto max-w-6xl"><SectionTitle center>E-Learning Experience</SectionTitle><div className="mt-12 grid items-center gap-10 md:grid-cols-[1.2fr_.8fr]"><Image src="/api/media/assets/E-learning_Journey-768x431.jpg" alt="EYEG e-learning journey" width={768} height={431} className="w-full shadow-xl"/><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#168ac2]">Learning beyond the classroom</p><h3 className="heading mt-3 text-3xl text-slate-800">Curious minds learn everywhere.</h3><p className="mt-5 leading-7 text-slate-600">Guided discovery, play and age-appropriate digital experiences keep children engaged wherever learning happens.</p><Link className="mt-7 inline-flex rounded-lg bg-[#168ac2] px-6 py-3 text-sm font-black text-white" href="/contact-us">Get In Touch</Link></div></div><div className="mt-12"><Gallery images={galleries} columns="lg:grid-cols-5"/></div></div></section>
<section className="bg-[#43cec9] px-5 py-12 text-white sm:px-8 lg:px-14"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 text-center sm:flex-row sm:text-left"><div><p className="text-xs font-black uppercase tracking-[.2em]">Start your child’s learning journey</p><h2 className="heading mt-2 text-3xl">Admissions are now open.</h2></div><a className="rounded-lg bg-white px-6 py-3 text-sm font-black text-[#168a91]" href="https://wa.me/971566990985">Enquire on WhatsApp</a></div></section></main>}
